language: python
python:
    - "3.6"
    - "3.7"
before_install:
    - sudo apt-get -y install libdbus-glib-1-dev
install:
    - pip install -U pip dbus-python mock flake8 coverage coveralls bluedot
script:
    - flake8 .
    - coverage run --source=rpi_sdr_replay setup.py test
after_success:
    - coveralls
