#!/usr/bin/env python3

import sys
import os.path
import argparse

import bluedot

from rpi_sdr_replay import Replayer, ReplayerBluetoothUI, FREQUENCY


DESCRIPTION = "Raspberry Pi based bluetooth controlled radio signal replayer"
DEFAULT_DIR = "~/sdr-recordings"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument(
        "-f",
        "--frequency",
        type=int,
        default=FREQUENCY,
        help="Set frequency in Hz for both RX & TX (Default: %(default)s)"
    )
    parser.add_argument(
        "-r",
        "--rx-frequency",
        default=None,
        help="Set RX frequency in Hz"
    )
    parser.add_argument(
        "-t",
        "--tx-frequency",
        default=None,
        help="Set TX frequency in Hz"
    )
    parser.add_argument(
        "-p",
        "--allow-pairing",
        action="store_true",
        default=False,
        help="Allow bluetooth pairing for the first 60sec after start"
    )
    parser.add_argument(
        "-d",
        "--dir",
        default=DEFAULT_DIR,
        help="Directory where to store the recordings"
    )

    args = parser.parse_args()

    # Check args

    args.dir = os.path.normpath(os.path.realpath(os.path.os.path.expanduser(args.dir)))

    if args.dir == os.path.normpath(os.path.realpath(os.path.os.path.expanduser(DEFAULT_DIR))):
        # Create the default destination directory
        if not os.path.exists(args.dir):
            os.mkdir(args.dir, mode=755)

    # Check the specified directly
    if not os.path.exists(args.dir):
        parser.error(f"The path '{args.dir} doesn't exist!'")
    if not os.path.isdir(args.dir):
        parser.error(f"The path '{args.dir}' is not a directory!")

    # Assign the frequencies
    rx_freq = args.frequency
    tx_freq = args.frequency

    if args.rx_frequency is not None:
        if not args.rx_frequency.isdigit():
            parser.error(f"The '{args.rx_frequency}' is not an integer number")
        rx_freq = int(args.rx_frequency)

    if args.tx_frequency is not None:
        if not args.tx_frequency.isdigit():
            parser.error(f"The '{args.tx_frequency}' is not an integer number")
        tx_freq = int(args.tx_frequency)

    # Check the RX frequency (RTL-SDR dongles can handle between 500 kHz - 1.75 GHz)
    if rx_freq < 500000 or rx_freq > 1750000000:
        parser.error(f"RX frequency must be between 500000-1750000000 (You specified {rx_freq})")

    # Check the TX frequency (rpitx can handle 5kHz - 1500MHz)
    if tx_freq < 5000 or tx_freq > 1500000000:
        parser.error(f"TX frequency must be between 5000-1500000000 (You specified {tx_freq})")

    # Instantiate bluetooth interface
    try:
        bd = bluedot.BlueDot()
    except Exception as err:
        print(f"Cannot setup a bluetooth server: {err}")
        sys.exit(1)

    # Run the bluetooth server and UI
    replayer = Replayer(args.dir, rx_freq, tx_freq)
    ui = ReplayerBluetoothUI(replayer, bd, args.allow_pairing)
    ui.run()
